# Full Feature Template for img2img
# img2img用のフル機能テンプレート
name: full_template_img2img
description: Complete template with all available extensions for img2img
type: img2img

base_settings:
  # img2img特有の設定
  init_images: []  # base64 encoded images or file paths
  denoising_strength: 0.75  # 0.0 = 元画像そのまま, 1.0 = 完全に新規生成
  resize_mode: 0  # 0=Just resize, 1=Crop and resize, 2=Resize and fill, 3=Just resize (latent upscale)

  # マスク関連（inpaint用）
  mask: ""  # base64 encoded mask
  mask_blur: 4
  mask_blur_x: 4
  mask_blur_y: 4
  inpainting_fill: 0  # 0=fill, 1=original, 2=latent noise, 3=latent nothing
  inpaint_full_res: true
  inpaint_full_res_padding: 32
  inpainting_mask_invert: 0

  # img2img共通設定
  prompt_suffix: ", masterpiece, best quality"
  negative_prompt: "lowres, bad anatomy, bad hands"
  steps: 20
  cfg_scale: 7.0
  width: 1024
  height: 1024
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"
  batch_size: 1
  n_iter: 1
  seed: -1
  subseed: -1
  subseed_strength: 0
  seed_resize_from_h: -1
  seed_resize_from_w: -1

  # モデル設定
  model: "animagineXL40_v40"
  vae: "Automatic"
  clip_skip: 2

  # その他の設定
  restore_faces: false
  tiling: false
  eta: 0
  s_churn: 0
  s_tmax: 0
  s_tmin: 0
  s_noise: 1

  # img2img alternative test
  image_cfg_scale: 0  # alternative test用

  # Sketch関連（img2img sketch用）
  sketch: ""  # base64 encoded sketch

extensions:
  # img2imgでも同じ拡張機能が使用可能
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed face"
        confidence: 0.3
        mask_blur: 4
        dilate_erode: 4
        inpaint_only_masked: true
        inpaint_padding: 32

      - model: "hand_yolov8n.pt"
        prompt: "perfect hands"
        confidence: 0.3
        mask_blur: 4
        dilate_erode: 4
        inpaint_only_masked: true
        inpaint_padding: 32

  controlnet:
    enabled: true
    units:
      # img2imgではreference onlyなども有効
      - enabled: true
        module: "reference_only"
        model: ""  # reference_onlyではモデル不要
        weight: 0.5
        resize_mode: "Crop and Resize"
        control_mode: "Balanced"

      - enabled: true
        module: "ip-adapter_clip_sd15"
        model: "ip-adapter_sd15"
        weight: 1.0
        resize_mode: "Crop and Resize"
        control_mode: "Balanced"

  # Color Grading (img2img特有)
  color_grading:
    enabled: false
    factor: 1.0

  # Inpaint Difference (差分検出)
  inpaint_difference:
    enabled: false
    mask_blur: 4
    difference_threshold: 50

  # Soft Inpainting
  soft_inpainting:
    enabled: false
    mask_influence: 0.5
    difference_influence: 0.5
    difference_threshold: 0.5
    preserve_unmasked: true

  # Outpainting
  outpainting:
    enabled: false
    pixels_to_expand: 128
    mask_blur: 8
    direction: "all"  # all, left, right, up, down
    falloff_exponent: 1.0
    color_variation: 0.05

  # その他の拡張機能はtxt2imgと同様
  regional_prompter:
    enabled: false
    mode: "Matrix"
    split_mode: "Horizontal"
    split_ratio: "1,1"
    base_prompt: ""
    common_prompt: ""

  dynamic_prompts:
    enabled: false
    combinatorial: false
    max_generations: 1
    template: ""

  tiled_diffusion:
    enabled: false
    method: "MultiDiffusion"
    tile_width: 96
    tile_height: 96
    tile_overlap: 48
    tile_batch_size: 4

  tiled_vae:
    enabled: false
    encoder_tile_size: 512
    decoder_tile_size: 64
    fast_decoder: true
    fast_encoder: true
    color_fix: true