# Full Feature Template for txt2img
# txt2img用のフル機能テンプレート - 全ての拡張機能を含む
name: full_template_txt2img
description: Complete template with all available extensions for txt2img
type: txt2img

base_settings:
  # プロンプト設定
  prompt_suffix: ", masterpiece, best quality, very aesthetic"
  negative_prompt: "lowres, bad anatomy, bad hands, text, error, missing fingers"

  # 基本生成パラメータ
  steps: 28
  cfg_scale: 7.0
  width: 1024
  height: 1024
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"
  batch_size: 1
  n_iter: 1
  seed: -1
  subseed: -1
  subseed_strength: 0
  seed_resize_from_h: -1
  seed_resize_from_w: -1

  # モデル設定
  model: "animagineXL40_v40"
  vae: "Automatic"
  clip_skip: 2

  # その他の設定
  restore_faces: false
  tiling: false
  eta: 0
  s_churn: 0
  s_tmax: 0
  s_tmin: 0
  s_noise: 1

  # Hires Fix設定
  enable_hr: true
  hr_scale: 2.0
  hr_upscaler: "R-ESRGAN 4x+ Anime6B"
  hr_second_pass_steps: 15
  hr_resize_x: 0
  hr_resize_y: 0
  denoising_strength: 0.45
  hr_prompt: ""
  hr_negative_prompt: ""

  # Refiner設定（SDXL用）
  refiner_checkpoint: ""
  refiner_switch_at: 0.8

extensions:
  # ADetailer - 最大3つのモデルを設定可能（サーバー設定による）
  adetailer:
    enabled: true
    models:
      # 1つ目のモデル（顔）
      - model: "face_yolov8n.pt"
        prompt: "detailed face, beautiful eyes"
        negative_prompt: ""
        confidence: 0.3
        mask_blur: 4
        dilate_erode: 4
        x_offset: 0
        y_offset: 0
        mask_merge_invert: "None"
        mask_preprocessor: "None"
        inpaint_only_masked: true
        inpaint_padding: 32
        use_separate_width: false
        width: 512
        use_separate_height: false
        height: 512
        use_separate_cfg_scale: false
        cfg_scale: 7.0
        use_separate_steps: false
        steps: 28
        use_separate_checkpoint: false
        checkpoint: ""
        use_separate_vae: false
        vae: ""
        use_separate_sampler: false
        sampler: "DPM++ 2M"
        scheduler: "Automatic"
        use_separate_clip_skip: false
        clip_skip: 1
        restore_faces_after: false
        controlnet_model: "None"

      # 2つ目のモデル（手）
      - model: "hand_yolov8n.pt"
        prompt: "detailed hand, perfect fingers"
        negative_prompt: "bad hands, extra fingers"
        confidence: 0.3
        mask_blur: 4
        dilate_erode: 4
        inpaint_only_masked: true
        inpaint_padding: 32

      # 3つ目のモデル（全身）
      - model: "person_yolov8n-seg.pt"
        prompt: ""
        negative_prompt: ""
        confidence: 0.3
        mask_blur: 4
        dilate_erode: 4
        inpaint_only_masked: false

  # ControlNet - 最大3ユニット（サーバー設定による）
  controlnet:
    enabled: true
    units:
      # Unit 0 - OpenPose
      - enabled: true
        module: "openpose_full"
        model: "control_v11p_sd15_openpose"
        weight: 1.0
        image: ""  # base64 or file path
        resize_mode: "Crop and Resize"
        low_vram: false
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        guidance_start: 0.0
        guidance_end: 1.0
        pixel_perfect: true
        control_mode: "Balanced"
        hr_option: "Both"
        save_detected_map: true

      # Unit 1 - Depth
      - enabled: true
        module: "depth_midas"
        model: "control_v11f1p_sd15_depth"
        weight: 0.5
        resize_mode: "Crop and Resize"
        processor_res: 512
        guidance_start: 0.0
        guidance_end: 1.0
        pixel_perfect: false
        control_mode: "My prompt is more important"

      # Unit 2 - Canny
      - enabled: false
        module: "canny"
        model: "control_v11p_sd15_canny"
        weight: 0.5
        resize_mode: "Crop and Resize"
        processor_res: 512
        threshold_a: 100
        threshold_b: 200
        guidance_start: 0.0
        guidance_end: 1.0
        pixel_perfect: false
        control_mode: "Balanced"

  # Regional Prompter
  regional_prompter:
    enabled: false
    mode: "Matrix"  # Matrix, Mask, Prompt
    split_mode: "Horizontal"  # Horizontal, Vertical, Random
    split_ratio: "1,1"
    base_prompt: "masterpiece, best quality"
    common_prompt: "detailed, aesthetic"
    lora_in_common: true
    lora_in_negative: false
    disable_convert_and: false
    use_base: false
    use_common: true
    use_negative_common: false

    # Matrix mode specific
    regions:
      - "1girl, red hair"
      - "blue sky, clouds"

    # Mask mode specific
    mask_path: ""

    # Prompt mode specific
    prompt_mode_prompt: "BREAK"

  # Dynamic Prompts
  dynamic_prompts:
    enabled: false
    combinatorial: false
    max_generations: 1
    enable_jinja_templates: false
    unlink_seed: false
    template: |
      {red|blue|green} hair,
      {smile|serious|crying} expression,
      {indoor|outdoor|forest|city} background

    # Wildcard settings
    wildcard_folder: "./wildcards"
    wildcards:
      hair_color: ["red", "blue", "green", "blonde", "black"]
      expression: ["smile", "serious", "crying", "angry", "surprised"]

  # Latent Couple (複数キャラクター生成)
  latent_couple:
    enabled: false
    divisions: 2
    positions: ["0:0.5", "0.5:1.0"]
    weights: [1.0, 1.0]
    prompts:
      - "1girl, red hair, left side"
      - "1girl, blue hair, right side"

  # Tiled Diffusion (大規模画像生成)
  tiled_diffusion:
    enabled: false
    method: "MultiDiffusion"
    tile_width: 96
    tile_height: 96
    tile_overlap: 48
    tile_batch_size: 4
    upscaler: "R-ESRGAN 4x+ Anime6B"
    scale_factor: 2.0

  # Tiled VAE (メモリ効率化)
  tiled_vae:
    enabled: false
    encoder_tile_size: 512
    decoder_tile_size: 64
    fast_decoder: true
    fast_encoder: true
    color_fix: true

  # Ultimate SD Upscale
  ultimate_upscale:
    enabled: false
    target_size_type: "Scale from image size"
    upscaler_index: "R-ESRGAN 4x+ Anime6B"
    scale: 2
    tile_width: 512
    tile_height: 512
    mask_blur: 8
    padding: 32
    seams_fix_width: 64
    seams_fix_padding: 16
    seams_fix_denoise: 0.35
    seams_fix_mask_blur: 8
    seams_fix_type: "None"

  # Self Attention Guidance
  self_attention_guidance:
    enabled: false
    scale: 0.75
    blur: 2

  # FreeU
  freeu:
    enabled: false
    b1: 1.2
    b2: 1.4
    s1: 0.9
    s2: 0.2