# ================================================================================================
# (02) Ultimate Dynamic Preset IMG2IMG - Complete Parameterization for All SD WebUI Reforge Features
# ================================================================================================
#
# This preset represents a revolutionary approach to AI image generation configuration.
# Instead of creating dozens of specialized presets, this single preset handles infinite
# combinations through dynamic parameter overrides.
#
# ================================================================================================
# USAGE EXAMPLES:
# ================================================================================================
#
# Basic IMG2IMG Generation:
#   init_image="input.png"
#   prompt="anime girl portrait"
#   denoising_strength=0.5
#   seed=12345
#
# Strong Transformation:
#   init_image="photo.png"
#   prompt="anime style artwork"
#   denoising_strength=0.75
#
# Inpaint Mode (Masked Editing):
#   init_image="original.png"
#   mask_image="mask.png"  # White=edit, Black=preserve
#   prompt="blue sky with clouds"
#   mask_blur=8
#   inpainting_fill=1  # Use original
#   inpaint_full_res=true
#
# ControlNet Single Unit:
#   prompt="colorful anime girl"
#   controlnet_image="pose.png"
#   controlnet_model_1="CN-anytest3_animagine4_A"
#   controlnet_weight_1=0.8
#
# ControlNet Multi-Unit:
#   prompt="anime girl in water"
#   controlnet_image="pose.png"
#   controlnet_image_2="style.png"
#   controlnet_image_3="effect.png"
#   controlnet_model_1="CN-posetest_v2_1"
#   controlnet_model_2="CN-anytest4_animagine4_A"
#   controlnet_weight_1=0.5
#   controlnet_weight_2=0.6
#
#
# ADetailer Customization:
#   prompt="anime girl full body"
#   adetailer_model_2="hand_yolov8n.pt"
#   adetailer_model_3="person_yolov8n-seg.pt"
#
# Batch Generation:
#   prompt="anime girl variations"
#   batch_size=4
#   n_iter=2
#   # Generates 8 images total (4 parallel x 2 iterations)
#
# Dynamic Prompts Expansion:
#   prompt="{cute|beautiful|elegant} anime girl with {red|blue|black} hair"
#   enable_dynamic_prompts=true
#   batch_size=4
#   # Automatic prompt expansion for each image
#
# Magic Prompt Enhancement:
#   prompt="anime girl"
#   enable_dynamic_prompts=true
#   magic_prompt=true
#   # AI automatically enhances and details the prompt
#
# Regional Prompter Matrix Mode:
#   prompt="2 girls ADDBASE red hair, blue eyes ADDCOL green hair, red eyes"
#   rp_active=true
#   rp_mode="Matrix"
#   rp_matrix_submode="Columns"
#   rp_divide_ratio="1,1"
#
# Regional Prompter Mask Mode:
#   prompt="fantasy warrior"
#   rp_active=true
#   rp_mode="Mask"
#   rp_mask_1="face_area.png"
#   rp_mask_2="body_area.png"
#   rp_prompt_1="beautiful detailed face"
#   rp_prompt_2="golden armor"
#
# Complete Feature Combination IMG2IMG:
#   init_image="base.png"
#   prompt="masterpiece {cute|cool} anime girl ADDBASE red hair ADDCOL blue hair"
#   denoising_strength=0.6
#   controlnet_image="pose.png"
#   controlnet_model_1="CN-anytest3_animagine4_A"
#   adetailer_model_2="hand_yolov8n.pt"
#   enable_dynamic_prompts=true
#   rp_active=true
#   rp_divide_ratio="1,1"
#   batch_size=2
#   n_iter=3
#
# ================================================================================================

name: img2img_dynamic
type: img2img
description: "Ultimate dynamic IMG2IMG preset - ControlNet (0-3 units) + ADetailer (1-4 models) + Full parameterization"

base_settings:
  # IMG2IMG specific parameters
  init_images: []  # Will be provided at runtime
  denoising_strength: 0.5  # Default strength, can be overridden
  resize_mode: 0  # 0=Just resize, 1=Crop and resize, 2=Resize and fill

  # Inpaint Mode parameters (optional - only used when mask_image is provided)
  # mask: ""  # Mask image will be set at runtime when mask_image param is provided
  # mask_blur: 4  # Override with mask_blur param
  # inpainting_fill: 1  # 0=fill, 1=original, 2=latent noise, 3=latent nothing
  # inpaint_full_res: true  # Process only masked area (true) or whole image (false)
  # inpaint_full_res_padding: 0  # Padding pixels around mask
  # inpainting_mask_invert: 0  # 0=normal, 1=invert

  # IMG2IMG Upscale options (alternative to Hires Fix)
  # Use larger width/height values to upscale
  # Example: 1024x1024 input → 2048x2048 output for 2x upscale

  # Common parameters
  checkpoint: "sd_animagineXL40_v4Opt"
  sampler_name: "Euler a"
  scheduler: "Automatic"
  steps: 28
  cfg_scale: 5
  width: 1024
  height: 1024
  seed: -1
  batch_size: 1
  n_iter: 1
  clip_skip: 1

prompt_template:
  positive_prefix: ""
  positive_suffix: "masterpiece, high score, great score, absurdres"
  negative: "lowres, bad anatomy, bad hands, text, error, missing finger, extra digits, fewer digits, cropped, worst quality, low quality, low score, bad score, average score, signature, watermark, username, blurry"

# ================================================================================================
# EXTENSIONS CONFIGURATION (Default values - override with parameters)
# ================================================================================================

extensions:
  # ADetailer: Face/Hand/Person/Eye Detection and Enhancement
  # Usage: Specify adetailer_model_2/3/4 to enable additional models
  # Example: adetailer_model_2="hand_yolov8n.pt" enables face+hand detection
  adetailer:
    enabled: true
    models:
      # Model 1: Always enabled - Face detection (default)
      - model: "face_yolov8n.pt"
        confidence: 0.3

      # Model 2: Template (enabled via adetailer_model_2 parameter)
      # Common options: "hand_yolov8n.pt", "person_yolov8n-seg.pt"
      - model: "hand_yolov8n.pt"
        confidence: 0.3
        enabled: false

      # Model 3: Template (enabled via adetailer_model_3 parameter)
      # Common options: "person_yolov8n-seg.pt", "mediapipe_face_mesh_eyes_only"
      - model: "person_yolov8n-seg.pt"
        confidence: 0.3
        enabled: false

      # Model 4: Template (enabled via adetailer_model_4 parameter)
      # Common options: "eye_yolov8n.pt", "mediapipe_face_mesh_eyes_only"
      - model: "eye_yolov8n.pt"
        confidence: 0.3
        enabled: false

  # ControlNet: Image Structure Control (0-3 units)
  # Usage: Provide controlnet_image/controlnet_image_2/controlnet_image_3 to enable units
  # Override: controlnet_model_1/2/3, controlnet_weight_1/2/3, controlnet_module_1/2/3
  # Models auto-resolve: "CN-anytest3_animagine4_A" → "CN-anytest3_animagine4_A [9ca08fae]"
  controlnet:
    enabled: true
    units:
      # Unit 0: Primary control (enabled when controlnet_image provided)
      # Override with: controlnet_model_1, controlnet_weight_1, controlnet_module_1
      - module: "None"  # "None"=preprocessed, "canny"=edge, "openpose"=pose
        model: "CN-anytest3_animagine4_A"  # Will auto-resolve to full name with hash
        weight: 1.0     # Control strength (0.0-2.0)
        guidance_start: 0.0
        guidance_end: 1.0
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: true

      # Unit 1: Secondary control (enabled when controlnet_image_2 provided)
      # Override with: controlnet_model_2, controlnet_weight_2, controlnet_module_2
      - module: "None"
        model: "CN-anytest3_animagine4_B"
        weight: 1.0
        guidance_start: 0.0
        guidance_end: 0.7   # Ends earlier for subtle effect
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: false

      # Unit 2: Tertiary control (enabled when controlnet_image_3 provided)
      # Override with: controlnet_model_3, controlnet_weight_3, controlnet_module_3
      - module: "None"
        model: "CN-anytest4_animagine4_A"
        weight: 1.0
        guidance_start: 0.0
        guidance_end: 0.5   # Subtle effect only
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: false

  # Dynamic Prompts: Automatic prompt expansion and variation
  # Usage: Use {option1|option2} syntax in prompts for automatic expansion
  # Override with: enable_dynamic_prompts, magic_prompt, combinatorial_generation, max_generations
  dynamic_prompts:
    enable_dynamic_prompts: true    # Default enabled for creative expansion
    combinatorial_generation: false
    max_generations: 0             # 0 = unlimited
    magic_prompt: false

  # Regional Prompter: Region-based prompt control (Matrix & Mask modes)
  # Usage Matrix: "2 girls ADDBASE red hair ADDCOL green hair" or "sky BREAK mountains BREAK lake"
  # Usage Mask: Provide rp_mask_1, rp_mask_2 with corresponding rp_prompt_1, rp_prompt_2
  # Override with: rp_active, rp_mode, rp_matrix_submode, rp_divide_ratio, rp_calc_mode
  regional_prompter:
    rp_active: false               # Default disabled (optional feature)
    rp_debug: false
    rp_mode: "Matrix"              # "Matrix" or "Mask"
    rp_matrix_submode: "Columns"   # "Columns", "Rows", "Cols;Rows"
    rp_mask_submode: "Mask"
    rp_prompt_submode: "Prompt"
    rp_divide_ratio: "1,1"         # Split ratios (e.g., "1,1" = 50/50, "1,2,1" = 25/50/25)
    rp_base_ratio: "0.2"           # Base influence (0.0-1.0)
    rp_use_base: true
    rp_use_common: false
    rp_use_ncommon: false
    rp_calc_mode: "Attention"      # "Attention" (soft) or "Latent" (hard)
    rp_not_change_and: false
    rp_lora_stop_step: "0"
    rp_lora_hires_stop_step: "0"
    rp_threshold: "0.4"