# (24) txt2img with multiple detection models
name: txt2img_animagine_multi_detect
type: txt2img
description: "txt2img with animagineXL40_v4Opt + ADetailer (face, hand, person, eyes)"

base_settings:
  checkpoint: "sd_animagineXL40_v4Opt"
  sampler_name: "Euler a"
  scheduler: "Automatic"
  steps: 28
  cfg_scale: 5
  width: 1024
  height: 1024
  seed: -1
  batch_size: 1
  n_iter: 1
  enable_hr: false
  denoising_strength: 0.4
  clip_skip: 2

prompt_template:
  positive_prefix: ""
  positive_suffix: "masterpiece, high score, great score, absurdres"
  negative: "lowres, bad anatomy, bad hands, text, error, missing finger, extra digits, fewer digits, cropped, worst quality, low quality, low score, bad score, average score, signature, watermark, username, blurry"

extensions:
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        confidence: 0.3
      - model: "hand_yolov8n.pt"
        confidence: 0.3
      - model: "person_yolov8n-seg.pt"
        confidence: 0.3
      - model: "eyes_yolov8n.pt"  # 目の詳細検出（存在する場合）
        confidence: 0.3