# ================================================================================================
# (26) Ultimate Dynamic Preset - Complete Parameterization for All SD WebUI Reforge Features
# ================================================================================================
#
# This preset represents a revolutionary approach to AI image generation configuration.
# Instead of creating dozens of specialized presets, this single preset handles infinite
# combinations through dynamic parameter overrides.
#
# ================================================================================================
# USAGE EXAMPLES:
# ================================================================================================
#
# Basic Generation (no extra features):
#   prompt="anime girl portrait"
#   seed=12345
#
# High-Resolution Generation:
#   prompt="anime girl portrait"
#   enable_hr=true
#   hr_scale=2.0
#   hr_upscaler="4x_fatal_Anime_500000_G"
#
# ControlNet Single Unit:
#   prompt="colorful anime girl"
#   controlnet_image="pose.png"
#   controlnet_model_1="CN-anytest3_animagine4_A"
#   controlnet_weight_1=0.8
#
# ControlNet Multi-Unit:
#   prompt="anime girl in water"
#   controlnet_image="pose.png"
#   controlnet_image_2="style.png"
#   controlnet_image_3="effect.png"
#   controlnet_model_1="CN-posetest_v2_1"
#   controlnet_model_2="CN-anytest4_animagine4_A"
#   controlnet_weight_1=0.5
#   controlnet_weight_2=0.6
#
#
# ADetailer Customization:
#   prompt="anime girl full body"
#   adetailer_model_2="hand_yolov8n.pt"
#   adetailer_model_3="person_yolov8n-seg.pt"
#
# Batch Generation:
#   prompt="anime girl variations"
#   batch_size=4
#   n_iter=2
#   # Generates 8 images total (4 parallel x 2 iterations)
#
# Dynamic Prompts Expansion:
#   prompt="{cute|beautiful|elegant} anime girl with {red|blue|black} hair"
#   enable_dynamic_prompts=true
#   batch_size=4
#   # Automatic prompt expansion for each image
#
# Magic Prompt Enhancement:
#   prompt="anime girl"
#   enable_dynamic_prompts=true
#   magic_prompt=true
#   # AI automatically enhances and details the prompt
#
# Complete Feature Combination:
#   prompt="masterpiece {cute|cool} anime girl"
#   enable_hr=true
#   hr_scale=1.5
#   controlnet_image="pose.png"
#   controlnet_model_1="CN-anytest3_animagine4_A"
#   adetailer_model_2="hand_yolov8n.pt"
#   enable_dynamic_prompts=true
#   batch_size=2
#   n_iter=3
#
# ================================================================================================

name: txt2img_cn_multi_3units
type: txt2img
description: "Ultimate dynamic preset - ControlNet (0-3 units) + ADetailer (1-4 models) + Hires Fix + Full parameterization"

base_settings:
  checkpoint: "sd_animagineXL40_v4Opt"
  sampler_name: "Euler a"
  scheduler: "Automatic"
  steps: 28
  cfg_scale: 5
  width: 1024
  height: 1024
  seed: -1
  batch_size: 1
  n_iter: 1
  enable_hr: false
  denoising_strength: 0.4
  clip_skip: 2

  # Hires Fix default settings (user can override)
  hr_scale: 2.0
  hr_upscaler: "R-ESRGAN 4x+ Anime6B"
  hr_second_pass_steps: 0
  hr_resize_x: 0
  hr_resize_y: 0

prompt_template:
  positive_prefix: ""
  positive_suffix: "masterpiece, high score, great score, absurdres"
  negative: "lowres, bad anatomy, bad hands, text, error, missing finger, extra digits, fewer digits, cropped, worst quality, low quality, low score, bad score, average score, signature, watermark, username, blurry"

# ================================================================================================
# EXTENSIONS CONFIGURATION (Default values - override with parameters)
# ================================================================================================

extensions:
  # ADetailer: Face/Hand/Person/Eye Detection and Enhancement
  # Usage: Specify adetailer_model_2/3/4 to enable additional models
  # Example: adetailer_model_2="hand_yolov8n.pt" enables face+hand detection
  adetailer:
    enabled: true
    models:
      # Model 1: Always enabled - Face detection (default)
      - model: "face_yolov8n.pt"
        confidence: 0.3

      # Model 2: Template (enabled via adetailer_model_2 parameter)
      # Common options: "hand_yolov8n.pt", "person_yolov8n-seg.pt"
      - model: "hand_yolov8n.pt"
        confidence: 0.3
        enabled: false

      # Model 3: Template (enabled via adetailer_model_3 parameter)
      # Common options: "person_yolov8n-seg.pt", "mediapipe_face_mesh_eyes_only"
      - model: "person_yolov8n-seg.pt"
        confidence: 0.3
        enabled: false

      # Model 4: Template (enabled via adetailer_model_4 parameter)
      # Common options: "eye_yolov8n.pt", "mediapipe_face_mesh_eyes_only"
      - model: "eye_yolov8n.pt"
        confidence: 0.3
        enabled: false

  # ControlNet: Image Structure Control (0-3 units)
  # Usage: Provide controlnet_image/controlnet_image_2/controlnet_image_3 to enable units
  # Override: controlnet_model_1/2/3, controlnet_weight_1/2/3, controlnet_module_1/2/3
  # Models auto-resolve: "CN-anytest3_animagine4_A" → "CN-anytest3_animagine4_A [9ca08fae]"
  controlnet:
    enabled: true
    units:
      # Unit 0: Primary control (enabled when controlnet_image provided)
      # Override with: controlnet_model_1, controlnet_weight_1, controlnet_module_1
      - module: "None"  # "None"=preprocessed, "canny"=edge, "openpose"=pose
        model: "CN-anytest3_animagine4_A"  # Will auto-resolve to full name with hash
        weight: 1.0     # Control strength (0.0-2.0)
        guidance_start: 0.0
        guidance_end: 1.0
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: true

      # Unit 1: Secondary control (enabled when controlnet_image_2 provided)
      # Override with: controlnet_model_2, controlnet_weight_2, controlnet_module_2
      - module: "None"
        model: "CN-anytest3_animagine4_B"
        weight: 0.8
        guidance_start: 0.0
        guidance_end: 0.7   # Ends earlier for subtle effect
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: false

      # Unit 2: Tertiary control (enabled when controlnet_image_3 provided)
      # Override with: controlnet_model_3, controlnet_weight_3, controlnet_module_3
      - module: "None"
        model: "CN-anytest4_animagine4_A"
        weight: 0.6
        guidance_start: 0.0
        guidance_end: 0.5   # Subtle effect only
        control_mode: 0
        pixel_perfect: true
        processor_res: 512
        threshold_a: 64
        threshold_b: 64
        enabled: false

  # Dynamic Prompts: Automatic prompt expansion and variation
  # Usage: Use {option1|option2} syntax in prompts for automatic expansion
  # Override with: enable_dynamic_prompts, magic_prompt, combinatorial_generation, max_generations
  dynamic_prompts:
    enable_dynamic_prompts: true    # Default enabled for creative expansion
    combinatorial_generation: false
    max_generations: 0             # 0 = unlimited
    magic_prompt: false