# Pencil Sketch/Drawing Style Preset
# Optimized for creating pencil sketch and drawing style artwork
# Best for: Concept sketches, artistic studies, monochrome illustrations

name: art_pencil_sketch
type: txt2img
description: "Pencil sketch and drawing style with detailed linework"

base_settings:
  # Model: General purpose model
  checkpoint: "v1-5-pruned-emaonly"  # Will fall back to default if not available

  # Sampler for line art
  sampler_name: "Euler"
  scheduler: "Simple"

  # Generation parameters
  steps: 20
  cfg_scale: 10
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "pencil sketch, pencil drawing, graphite, sketch, drawing, monochrome, lineart"
  positive_suffix: "detailed lines, cross-hatching, shading, traditional art, paper texture, artistic"
  negative: "color, photo, painting, 3d render, anime, watercolor, oil painting, colored, worst quality, low quality, normal quality, lowres, blurry, text, watermark, signature"

# Optional extensions
extensions:
  # No ADetailer for sketch style
  adetailer:
    enabled: false

  # ControlNet can be useful for line guidance
  controlnet:
    enabled: false
    units: []

  # Keep it simple for sketch effect
  hires_fix:
    enabled: false

  # No color adjustments needed
  dynamic_prompts:
    enabled: false