# Anime/Manga Style Artwork Preset
# Optimized for creating anime and manga style illustrations
# Best for: Character art, anime scenes, manga-style compositions

name: art_anime
type: txt2img
description: "Anime/manga style artwork with vibrant colors and characteristic features"

base_settings:
  # Model: Using an anime-specific model if available
  checkpoint: "aamAniMixAnime_v2"  # Will fall back to default if not available

  # Sampler optimized for anime style
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 20
  cfg_scale: 7
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings for better style consistency
  clip_skip: 2

prompt_template:
  positive_prefix: "anime artwork, anime style, key visual, vibrant, studio anime, highly detailed"
  positive_suffix: "masterpiece, best quality, very aesthetic, absurdres"
  negative: "photo, deformed, black and white, realism, disfigured, low contrast, bad anatomy, worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bw, bad photo, bad photography, bad art, watermark, signature, text, error, cropped"

# Optional extensions
extensions:
  # ADetailer for better face/hand quality
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed anime face, beautiful anime eyes, anime style face"
        confidence: 0.3

  # Dynamic Prompts for variety
  dynamic_prompts:
    enabled: false

  # Hires Fix can be enabled for higher quality
  hires_fix:
    enabled: false
    upscaler: "R-ESRGAN 4x+ Anime6B"
    upscale_by: 2
    denoising_strength: 0.4