# Oil Painting Style Preset
# Optimized for creating oil painting style artwork
# Best for: Classical portraits, landscapes, still life, fine art

name: art_oil_painting
type: txt2img
description: "Oil painting style with rich textures and classical techniques"

base_settings:
  # Model: General purpose with good artistic capabilities
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for artistic detail
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 30
  cfg_scale: 9
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.5

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "oil painting, oil on canvas, impasto, thick paint, brushstrokes, traditional art"
  positive_suffix: "masterpiece, fine art, museum quality, detailed brushwork, rich colors, dramatic lighting"
  negative: "photo, digital art, 3d render, anime, watercolor, sketch, bad art, amateur, worst quality, low quality, normal quality, lowres, simple background, plain, text, watermark, signature, frame"

# Optional extensions
extensions:
  # Minimal processing to maintain painterly quality
  adetailer:
    enabled: false

  # Can use ControlNet for composition
  controlnet:
    enabled: false

  # Optional Hires Fix for larger canvases
  hires_fix:
    enabled: false
    upscaler: "ESRGAN_4x"
    upscale_by: 1.5
    denoising_strength: 0.3
    steps: 20