# Photorealistic Style Preset
# Optimized for creating photorealistic images
# Best for: Realistic portraits, photographic scenes, lifelike renders

name: art_realistic
type: txt2img
description: "Photorealistic images with high detail and natural lighting"

base_settings:
  # Model: Using a realistic model
  checkpoint: "realisticVisionV60B1_v51VAE"  # Will fall back to default if not available

  # Sampler optimized for realism
  sampler_name: "DPM++ 2M SDE"
  scheduler: "Karras"

  # Generation parameters
  steps: 25
  cfg_scale: 5.5
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: true
  denoising_strength: 0.35

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "RAW photo, subject, 8k uhd, dslr, soft lighting, high quality, film grain"
  positive_suffix: "highly detailed, professional photograph, sharp focus"
  negative: "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, text, watermark, signature"

# Optional extensions
extensions:
  # ADetailer for better face quality
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed face, natural skin texture, realistic eyes"
        confidence: 0.3
        dilate_erode: 4

      - model: "hand_yolov8n.pt"
        prompt: "detailed hands, natural hand"
        confidence: 0.3

  # Hires Fix for better quality
  hires_fix:
    enabled: true
    upscaler: "4x-UltraSharp"
    upscale_by: 1.5
    denoising_strength: 0.35
    steps: 15