# Fantasy Art Preset
# Optimized for fantasy artwork with magical elements
# Best for: Fantasy characters, magical scenes, mythical creatures

name: creative_fantasy
type: txt2img
description: "Fantasy art with magical elements and epic compositions"

base_settings:
  # Model: General purpose or fantasy-oriented
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for detailed fantasy art
  sampler_name: "DPM++ 2M SDE"
  scheduler: "Karras"

  # Generation parameters
  steps: 30
  cfg_scale: 7.5
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "fantasy art, magical, epic fantasy, mystical, enchanted"
  positive_suffix: "highly detailed, digital painting, artstation, concept art, sharp focus, illustration, epic composition, magical atmosphere"
  negative: "photo, photorealistic, realism, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blurry, bad art, bad anatomy, worst quality, low quality, text, watermark"

# Optional extensions
extensions:
  # ADetailer for character faces
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed fantasy character face, magical eyes"
        confidence: 0.3

  # Dynamic Prompts for variety
  dynamic_prompts:
    enabled: false

  # Optional Hires Fix
  hires_fix:
    enabled: false
    upscaler: "R-ESRGAN 4x+"
    upscale_by: 1.5
    denoising_strength: 0.35