# Abstract Art Preset
# Optimized for abstract and experimental artwork
# Best for: Abstract compositions, experimental art, modern art

name: creative_abstract
type: txt2img
description: "Abstract art with experimental compositions and colors"

base_settings:
  # Model: General purpose
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for creative freedom
  sampler_name: "Euler"
  scheduler: "Simple"

  # Generation parameters
  steps: 20
  cfg_scale: 12  # Higher for more abstract
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.5

  # CLIP settings
  clip_skip: 2  # More abstract interpretation

prompt_template:
  positive_prefix: "abstract art, abstract, non-representational, modern art, contemporary art"
  positive_suffix: "geometric shapes, flowing forms, color field, experimental, artistic, creative composition, vibrant colors"
  negative: "realistic, photorealistic, portrait, face, person, landscape, recognizable objects, text, watermark, signature, worst quality, low quality"

# Optional extensions
extensions:
  # No face detection for abstract art
  adetailer:
    enabled: false

  # Pure abstract generation
  controlnet:
    enabled: false

  # Keep it simple
  hires_fix:
    enabled: false

  # Can enable for variations
  dynamic_prompts:
    enabled: false