# Science Fiction Art Preset
# Optimized for sci-fi themed artwork
# Best for: Futuristic scenes, spaceships, cyberpunk, technology

name: creative_scifi
type: txt2img
description: "Science fiction themed art with futuristic elements"

base_settings:
  # Model: General purpose
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for detailed sci-fi art
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 25
  cfg_scale: 7
  width: 1024
  height: 1024

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "science fiction, sci-fi, futuristic, cyberpunk, space art, technology"
  positive_suffix: "detailed, digital art, concept art, neon lighting, holographic, high tech, cinematic lighting"
  negative: "medieval, fantasy, magic, primitive, old, ancient, worst quality, low quality, normal quality, lowres, low details, oversaturated, undersaturated, overexposed, underexposed, grayscale, bw, bad photo, bad art, text, watermark"

# Optional extensions
extensions:
  # ADetailer for any human characters
  adetailer:
    enabled: false

  # Can enable for cyberpunk characters
  dynamic_prompts:
    enabled: false

  # Optional Hires Fix
  hires_fix:
    enabled: false
    upscaler: "R-ESRGAN 4x+"
    upscale_by: 1.5
    denoising_strength: 0.35