# Style Transfer Preset
# Optimized for transferring artistic styles to existing images
# Best for: Converting photos to art styles, artistic transformations

name: img2img_style_transfer
type: img2img
description: "Transfer artistic styles to existing images"

base_settings:
  # Model: Artistic model for style transfer
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for img2img
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 30
  cfg_scale: 7
  width: -1  # Use input image size
  height: -1  # Use input image size

  # Denoising for style transfer
  denoising_strength: 0.65  # Higher for more style transfer

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # CLIP settings
  clip_skip: 1

  # img2img specific
  resize_mode: 0  # Just resize
  inpainting_fill: 1  # Original

prompt_template:
  positive_prefix: "in the style of"
  positive_suffix: "artistic style, high quality, detailed"
  negative: "low quality, worst quality, blurry, distorted, deformed, amateur, text, watermark, signature"

# Optional extensions
extensions:
  # ADetailer can help preserve faces
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed face in artistic style"
        confidence: 0.3
        denoising_strength: 0.4

  # Can use ControlNet to preserve structure
  controlnet:
    enabled: false

  # No upscaling for style transfer
  hires_fix:
    enabled: false