# Portrait Photography Preset
# Optimized for professional portrait photography with face enhancement
# Best for: Headshots, fashion portraits, professional profiles

name: photo_portrait
type: txt2img
description: "Professional portrait photography with enhanced face details"

base_settings:
  # Model: Realistic model for portraits
  checkpoint: "realisticVisionV60B1_v51VAE"  # Will fall back to default if not available

  # Sampler for smooth skin and details
  sampler_name: "DPM++ 2M SDE"
  scheduler: "Karras"

  # Generation parameters
  steps: 30
  cfg_scale: 5
  width: 896
  height: 1152  # Portrait aspect ratio

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: true
  denoising_strength: 0.3

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "portrait photography, professional headshot, studio lighting, 85mm lens, f/1.8"
  positive_suffix: "highly detailed face, natural skin texture, catchlight in eyes, bokeh background, professional photo"
  negative: "bad anatomy, bad hands, bad face, deformed, ugly, mutilated, disfigured, poorly drawn face, mutation, mutated, extra limb, disgusting, poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed hands, long neck, mutated hands and fingers, bad hands, missing fingers, cropped, worst quality, low quality, normal quality, jpeg artifacts, text, watermark"

# Optional extensions
extensions:
  # ADetailer for enhanced face quality
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed face, natural skin texture, beautiful eyes, perfect face"
        negative_prompt: "bad face, ugly"
        confidence: 0.3
        dilate_erode: 4
        mask_blur: 4
        denoising_strength: 0.3
        inpaint_only_masked: true
        inpaint_padding: 32

      - model: "hand_yolov8n.pt"
        prompt: "detailed hands, perfect hands"
        confidence: 0.3

  # Hires Fix for better quality
  hires_fix:
    enabled: true
    upscaler: "4x-UltraSharp"
    upscale_by: 1.5
    denoising_strength: 0.3
    steps: 20