# Landscape Photography Preset
# Optimized for stunning landscape and nature photography
# Best for: Natural scenery, cityscapes, travel photography

name: photo_landscape
type: txt2img
description: "Landscape photography with vibrant colors and sharp details"

base_settings:
  # Model: Realistic model for landscapes
  checkpoint: "realisticVisionV60B1_v51VAE"  # Will fall back to default if not available

  # Sampler for crisp details
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 25
  cfg_scale: 6
  width: 1344
  height: 768  # Landscape aspect ratio

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: true
  denoising_strength: 0.35

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "landscape photography, wide angle, golden hour, dramatic sky, nature photography"
  positive_suffix: "sharp focus, high dynamic range, vibrant colors, professional photograph, award winning photo, depth of field"
  negative: "people, portrait, face, anime, cartoon, painting, illustration, drawing, art, sketch, worst quality, low quality, normal quality, lowres, blurry, text, watermark, signature, out of focus, depth of field blur, bokeh"

# Optional extensions
extensions:
  # No ADetailer for landscapes
  adetailer:
    enabled: false

  # Hires Fix for better quality
  hires_fix:
    enabled: true
    upscaler: "R-ESRGAN 4x+"
    upscale_by: 1.5
    denoising_strength: 0.35
    steps: 20

  # Optional ControlNet for composition
  controlnet:
    enabled: false

  # Can use Regional Prompter for sky/ground separation
  regional_prompter:
    enabled: false