# Product Photography Preset
# Optimized for clean, professional product photography
# Best for: E-commerce, advertising, catalog photography

name: photo_product
type: txt2img
description: "Clean product photography with studio lighting"

base_settings:
  # Model: Realistic model
  checkpoint: "realisticVisionV60B1_v51VAE"  # Will fall back to default if not available

  # Sampler for clean renders
  sampler_name: "DPM++ 2M SDE"
  scheduler: "Karras"

  # Generation parameters
  steps: 25
  cfg_scale: 4.5
  width: 1024
  height: 1024  # Square for products

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.3

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "product photography, studio lighting, white background, commercial photography, advertising photography"
  positive_suffix: "professional, clean, minimalist, high quality, sharp focus, product shot, centered, well lit"
  negative: "people, hands, face, messy, cluttered, busy background, text, watermark, signature, logo, brand, anime, cartoon, painting, drawing, sketch, worst quality, low quality, normal quality, blurry, out of focus"

# Optional extensions
extensions:
  # No ADetailer for products
  adetailer:
    enabled: false

  # Simple setup for clean product shots
  hires_fix:
    enabled: true
    upscaler: "ESRGAN_4x"
    upscale_by: 1.5
    denoising_strength: 0.25
    steps: 15

  # Can use ControlNet for precise product placement
  controlnet:
    enabled: false