# Book/Article Illustration Preset
# Optimized for editorial and book illustrations
# Best for: Book covers, magazine illustrations, educational materials

name: practical_illustration
type: txt2img
description: "Professional illustrations for books and articles"

base_settings:
  # Model: Artistic model
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for illustration quality
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 25
  cfg_scale: 7.5
  width: 896
  height: 1152  # Book cover ratio

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "illustration, digital illustration, book illustration, editorial illustration"
  positive_suffix: "professional illustration, detailed, colorful, storybook style, high quality artwork"
  negative: "photo, photorealistic, 3d render, worst quality, low quality, normal quality, lowres, blurry, text, watermark, signature, amateur"

# Optional extensions
extensions:
  # ADetailer for character illustrations
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "illustrated character face, storybook style"
        confidence: 0.3

  # Optional for higher resolution
  hires_fix:
    enabled: false
    upscaler: "R-ESRGAN 4x+"
    upscale_by: 1.5
    denoising_strength: 0.35

  # Can use for varied illustrations
  dynamic_prompts:
    enabled: false