# Texture/Pattern Generation Preset
# Optimized for creating seamless textures and patterns
# Best for: Game textures, fabric patterns, wallpapers, backgrounds

name: practical_texture
type: txt2img
description: "Seamless texture and pattern generation for various applications"

base_settings:
  # Model: General purpose
  checkpoint: "v1-5-pruned-emaonly"  # Will fall back to default if not available

  # Sampler for consistent patterns
  sampler_name: "DPM++ 2M"
  scheduler: "Karras"

  # Generation parameters
  steps: 20
  cfg_scale: 7
  width: 1024
  height: 1024  # Square for tileable textures

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

  # Tiling for seamless textures
  tiling: true

prompt_template:
  positive_prefix: "seamless texture, tileable, pattern, repeating pattern, texture"
  positive_suffix: "high quality, detailed texture, seamless, tileable, professional"
  negative: "seam, border, edge, frame, watermark, text, signature, logo, worst quality, low quality"

# Optional extensions
extensions:
  # No face detection for textures
  adetailer:
    enabled: false

  # Tiled Diffusion for better seamless generation
  tiled_diffusion:
    enabled: true
    method: "MultiDiffusion"
    tile_width: 128
    tile_height: 128
    tile_overlap: 32
    tile_batch_size: 4

  # No upscaling needed
  hires_fix:
    enabled: false