# Concept Art Preset
# Optimized for game and movie concept art
# Best for: Character designs, environment concepts, prop designs

name: practical_concept_art
type: txt2img
description: "Professional concept art for games and movies"

base_settings:
  # Model: Artistic model
  checkpoint: "dreamshaper_8"  # Will fall back to default if not available

  # Sampler for detailed art
  sampler_name: "DPM++ 2M SDE"
  scheduler: "Karras"

  # Generation parameters
  steps: 30
  cfg_scale: 7
  width: 1344
  height: 768  # Common concept art ratio

  # Seed (-1 for random)
  seed: -1

  # Batch settings
  batch_size: 1
  n_iter: 1

  # Quality settings
  enable_hr: false
  denoising_strength: 0.4

  # CLIP settings
  clip_skip: 1

prompt_template:
  positive_prefix: "concept art, digital painting, artstation, concept design, production art"
  positive_suffix: "professional, detailed, trending on artstation, concept art style, matte painting, sharp focus"
  negative: "photo, photorealistic, amateur, worst quality, low quality, normal quality, lowres, blurry, out of focus, text, watermark, signature"

# Optional extensions
extensions:
  # ADetailer for character concepts
  adetailer:
    enabled: true
    models:
      - model: "face_yolov8n.pt"
        prompt: "detailed character face, concept art style"
        confidence: 0.3

  # Can enable for larger concepts
  hires_fix:
    enabled: false
    upscaler: "R-ESRGAN 4x+"
    upscale_by: 1.5
    denoising_strength: 0.35

  # Dynamic Prompts for variations
  dynamic_prompts:
    enabled: false